# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baaff637bbfdc6453594879d2692ed693f42e81e27b6c4e18f4fa3272c48765629010a71abbafd7c668acf7d949e57fca3941901cc1109c13939507a1d9aa912

test:
  secret_key_base: 22db18f0e6f3107dea88844836ac2d54d0cfec02f002ac0e15d3c93a0057dbcbde1a34065bf2632c424200fde2bd34c6fa477d81fdbd64d3c58a30c211b92b9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
